### ISSUE TITLE
ctrees: there is an unexpected error when running the example code

### ISSUE THREAD

**Issue by qingjian1991** [caravagn/ctree#1]
Hi, giulio:

When I run the example code of ctrees, there is an unexpected error. The **x** is empty when successfully running the ctrees.

```R
#below is the exmaple code of ctree.
data('ctree_input')

x = ctrees(
   ctree_input$CCF_clusters,
   ctree_input$drivers,
   ctree_input$samples,
   ctree_input$patient,
   ctree_input$sspace.cutoff,
   ctree_input$n.sampling,
   ctree_input$store.max
   )
#there is no error when running this code, but the x is NULL, without any output. 
  
print(x[[1]]) 
#NULL
plot(x[[1]])
#error because of NULL
```
Any further modification will be appreciated.

Best,

Qingjian Chen
Sun Yat-Sen Univeristy Cancer Center

**Comment by caravagn** [comment]
Hello @qingjian1991, this does not happen to me. If I run your code I get everything right. Can you please report here all the I/O withe R session so I can check  what is happening?

**Comment by qingjian1991** [comment]
Hi, @caravagn , the code is now work well now, I reinstall the ctree package. There is another minor bug. The S3 seems not work well, **plot(x)** does not show the figure, whereas  **plot.ctree(x)** can show the trees.

**Comment by caravagn** [comment]
Yes I have noticed now, I now fixed NAMESPACE and should work. Thanks for reporting this.
