### ISSUE TITLE
ClonEvol_surrogate no longer produces adjacency matrix

### ISSUE THREAD

**Issue by mike8115** [caravagn/ctree#5]
Hello @caravagn and @l0ka 

It looks like there was some changes from 51b82397e31cf08c3f272252ed1c1d70924b573d that broke ClonEvol_surrogate(). At line 248, TR no longer calls CCF_phylogeny_univariate() because those lines were moved into the else-if statement.

Unfortunately, I don't think anyone would be able to create trees using the latest version of the code.

Best,
Michael

**Comment by caravagn** [comment]
Hello @mike8115 and @l0ka yes I think that there might have been some issues with a bracket. I should have fixed those now with the new commit. Could you check and let me know?

**Comment by mike8115** [comment]
Thanks for the fix! It looks good on my small set of data.
